package com.SIMOD.SIMOD.domain.enums;

public enum TipoNotificacao {
    INFO,
    ALERTA,
    URGENTE,
    VINCULO_SOLICITADO,
    VINCULO_ACEITADO,
    VINCULO_REJEITADO,
    VINCULO_DESFEITO,
    SESSAO_AGENDADA,
    SESSAO_DESMARCADA,
    SESSAO_CONFIRMADA,
    SESSAO_REJEITADA,
    SESSAO_CANCELADA,
    SESSAO_REAGENDADA,
}
