CREATE TABLE reminders(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID NOT NULL,
    type VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(500),
    scheduled_at TIMESTAMP NOT NULL,
    recurring BOOLEAN DEFAULT FALSE,
    interval_type VARCHAR(20),
    interval_hours INTEGER,
    confirmed BOOLEAN DEFAULT FALSE,
    confirmed_at TIMESTAMP,
    created_by VARCHAR(20) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    medicine_id UUID,
    diet_id UUID,
    activity_id UUID,
    session_id UUID,
    CONSTRAINT fk_reminder_patient FOREIGN KEY (patient_id) REFERENCES patient(id) ON DELETE CASCADE
);