CREATE TABLE notifications(
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    title VARCHAR(50),
    message TEXT NOT NULL,
    type VARCHAR(20) NOT NULL,
    read BOOLEAN DEFAULT FALSE,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_user
    FOREIGN KEY (id)
        REFERENCES users(id_user)
        ON DELETE CASCADE
);